### ISSUE TITLE
Audit of modifications

### ISSUE THREAD

**Issue by thomasLeclaire** [envkey/envkey-app#17] opened 2018-10-10 09:15 UTC
Today, use the application on production is highly risky. Modifications can be done easily without really consider the impact, and without way to rollback. 

nice features will be to have 
- Full audit of modifications done: Add, modification, removal,.. who did it, and when
- Possibility to activate double validation for some changes
- possibility to rollback a modification in one click

**Comment by danenania** [comment] 2018-10-10 19:17
Thanks @thomasEffilab - this is in the works!

**Comment by codeitcody** [comment] 2019-07-23 16:41
Good to hear!

Production issues are often caused by changes to environmental variables over code changes. Having a history of the environment  variables to enable easy rollback would be very useful.

**Comment by ctrlaltdylan** [comment] 2020-05-19 15:40
@danenania it's been a couple years - any progress on this?

**Comment by danenania** [comment] 2020-05-19 20:06
@ctrlaltdylan Yes, it will be included in our V2--already working nicely in development :) - release target is now set for Aug 1st. 2020.

**Comment by zjwhitehead** [comment] 2020-08-12 15:20
Excited to try this out @danenania. Let me know if you need testers!

**Comment by weber93** [comment] 2020-10-27 23:08
Checking on this.

**Comment by afrase** [comment] 2021-01-14 19:41
@danenania Any updates on this feature?
Thanks!

**Comment by danenania** [comment] 2021-01-15 00:00
@afrase @weber93 v2 is still in the works--it will include full audit logs. Getting close... stay tuned.

**Comment by michaelbridge** [comment] 2021-02-05 14:48
Great to hear this is being worked on; from my perspective, it is definitely the enhancement that would have the most significant impact on the product.

**Comment by danenania** [comment] 2022-03-30 20:14
EnvKey v2 is finally live, and includes audit logs: https://github.com/envkey/envkey

**Closed by danenania** 2022-03-30 20:14 UTC
Labels: enhancement
