### ISSUE TITLE
Got a blank white page when switching app

### ISSUE THREAD

**Issue by yhjor** [envkey/envkey-app#3] opened 2017-10-12 06:49 UTC
I have two apps in the application and it works fine after logging in and it opens the default one. However, when I switch it by clicking another project in the navigation, it becomes all white. Reopen it, it will open the default app again.

![2017-10-12 2 47 58](https://user-images.githubusercontent.com/1940853/31482833-6a4f19c4-af5c-11e7-89e1-c83ee0eb7a51.png)

**Comment by danenania** [comment] 2017-10-12 15:22
@yhjor What platform are you on? I'll investigate.

**Comment by danenania** [comment] 2017-10-12 15:38
@yhjor A couple questions:

- Did this occur immediately after creating the app or only later? 
- Did you rename the app?

**Comment by yhjor** [comment] 2017-10-12 15:51
It happens after I added the second app and close it. I reopen it next day, making some modification on current project and try to switch, the blank page will appear.

**Comment by danenania** [comment] 2017-10-12 16:06
Ok, I think I see the cause of the issue. Working on a fix.

**Comment by yhjor** [comment] 2017-10-12 16:07
Great! Thanks you.

**Comment by danenania** [comment] 2017-10-14 04:20
Navigation behavior is fixed in v1.0.3

**Closed by danenania** 2017-10-14 04:20 UTC

**Comment by natekratchman** [comment] 2018-03-15 21:01
@danenania confirmed this issue was related to trial ending. After upgrading, the app is now working again 👍 Probably still worthwhile looking into that modal overlay not showing!

**Comment by danenania** [comment] 2018-03-15 21:02
Yes, thanks for the heads up! Will get that fixed.
